# Node Image for docker on which code will execute
image: node:12

# This is the stages / task to perfom in jobs
stages:
  - build
  - upload
  
# caching for reuse 
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - node_modules/
  - build/

# Job One for making build
build_master:
  stage: build
  script:
  - npm install
  - npm run build 
  only: ['master']

# Job Two for deploy build to server
upload_master:
  stage: upload
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - chmod 400 $PRIVATE_KEY
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - apt-get update -y
    - apt-get -y install rsync
  script:
    - ssh -i $PRIVATE_KEY gitlab@$SERVER_IP
    - rsync -zvhr -auv -e "ssh -i $PRIVATE_KEY" build/ gitlab@$SERVER_IP:/var/www/frontend/app.worqplace.io
  only: ['master']
