/* USERS */
export const GET_BOARDS_LIST = 'GET_BOARDS_LIST';
export const GET_BOARDS_LIST_SUCCESS = 'GET_BOARDS_LIST_SUCCESS';

export const CREATE_BOARD = 'CREATE_BOARD';
export const CREATE_BOARD_SUCCESS = 'CREATE_BOARD_SUCCESS';

export const GET_BOARD_DETAIL = 'GET_BOARD_DETAIL';
export const GET_BOARD_DETAIL_SUCCESS = 'GET_BOARD_DETAIL_SUCCESS';

export const CREATE_TASK_LIST = 'CREATE_TASK_LIST';
export const CREATE_TASK_LIST_SUCCESS = 'CREATE_TASK_LIST_SUCCESS'

export const CREATE_TODO = 'CREATE-TODO';
export const CREATE_TODO_SUCCESS = 'CREATE_TODO_SUCCESS';