/* USERS */
export const GET_TEAMS_LIST = 'GET_TEAMS_LIST';
export const GET_TEAMS_LIST_SUCCESS = 'GET_TEAMS_LIST_SUCCESS';

export const CREATE_TEAM = 'CREATE_TEAM';
export const CREATE_TEAM_SUCCESS = 'CREATE_TEAM_SUCCESS';


export const CHANGE_SELECTED_TEAM_NAME = 'CHANGE_SELECTED_TEAM_NAME';


